### ISSUE TITLE
Menu option #6 does not work

### ISSUE THREAD

**Issue by chrisidso** [caiobran/mstables#9]
Saw this on linux (Ubuntu).   To repro:
Type 2 to add then enter a small number.  
When the menu reappears type 6 to create a back up file.   I typed 'lion7' ...

Expected:   Should allow you to type a file name and then create the desired back up file.
Actual:  Error message:  
=========================================
Please wait while the database file is backed-up ...

Traceback (most recent call last):
  File "main.py", line 161, in <module>
    main(db_file)
  File "main.py", line 121, in main
    msg = backup_db(db_file)
  File "main.py", line 22, in backup_db
    copyfile(db_file['path'], new_file)
  File "/home/newton/anaconda3/lib/python3.7/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'db/backup/lion7.sqlite'
===========================================================

**Comment by datatalking** [comment]
Please review issue#10 with the investpy potential new data source.
